Добавил бизнес-логику админа, также добавил плагин для автоматического создания мапперов.
SokolovAl/farmer-shop pull request #19
Opened 2022-12-05 16:59 UTC by UnimaginableCat

2022-12-05 17:27 UTC, PizzzaDog requested changes

2022-12-05 17:27 UTC, PizzzaDog commented on src/main/java/ru/aston/farmershop/entities/User.java
>  package ru.aston.farmershop.entities;
Setter access level

2022-12-05 17:27 UTC, PizzzaDog commented on src/main/java/ru/aston/farmershop/services/UserService.java
> +
Codestyle?

2022-12-05 17:27 UTC, PizzzaDog commented on src/main/java/ru/aston/farmershop/services/implementations/UserServiceImpl.java
> +            User user = optionalUser.get();
Mapper ok

2022-12-05 17:27 UTC, PizzzaDog commented on src/main/java/ru/aston/farmershop/controllers/AdminController.java
> +    @ResponseStatus(HttpStatus.CREATED)
Или статусы везде или не надо начинать

2022-12-05 17:27 UTC, PizzzaDog commented on pom.xml
> -         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Пощади табуляцию

2022-12-06 14:42 UTC, SokolovAl approved these changes

2022-12-07 11:45 UTC, SokolovAl approved these changes

2022-12-07 12:04 UTC, PizzzaDog approved these changes
Need changes but approve.

2022-12-07 12:04 UTC, PizzzaDog commented on pom.xml
> -         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Так и не пощадил? Ладно...

2022-12-07 12:04 UTC, PizzzaDog commented on src/main/java/ru/aston/farmershop/dto/UserDto.java
> +import ru.aston.farmershop.entities.User;
Это куда, это зачем?

2022-12-07 12:09 UTC, UnimaginableCat commented on src/main/java/ru/aston/farmershop/dto/UserDto.java
> +import ru.aston.farmershop.entities.User;
Для джавадока

2022-12-07 12:09 UTC, UnimaginableCat commented on src/main/java/ru/aston/farmershop/dto/UserDto.java
> +import ru.aston.farmershop.entities.User;
> Это куда, это зачем?

для джавадока

2022-12-07 12:15 UTC, merged